### ISSUE TITLE
LinAlgError when fitting with ``fix_scale=False``

### ISSUE THREAD

**Issue by djperrefort** [kboone/avocado#1]
I'm trying to fit CSP data using avocado. I've registered the wavelengths with the package and formatted the data in the way `avocado` expects but run into a linear algebra error.

```python
import avocado
from sndata.csp import dr3

# Get CSP data and add effective wavelengths to the instruments module
dr3.download_module_data()

for band_name, wavelength in zip(dr3.band_names, dr3.lambda_effective):
    avocado.instruments.band_central_wavelengths[band_name] = wavelength

# Construct input arguments for AstronomicalObject
data_table = dr3.get_data_for_id('2005kc', format_sncosmo=True)
observations = data_table.to_pandas()[['time', 'band', 'flux', 'fluxerr']]
observations.rename(columns={'fluxerr': 'flux_error'}, inplace=True)
meta = {
    'object_id': data_table.meta['obj_id'],
    'galactic': False,
    'host_photoz': data_table.meta['redshift'],
    'host_photoz_error': 0,
    'host_specz': data_table.meta['redshift'],
}

ast_obj = avocado.AstronomicalObject(meta, observations)
ast_obj.fit_gaussian_process()
```

This raises the following error:

```
>>> LinAlgError: 77-th leading minor of the array is not positive definite
```

which isn't informative at all. However the following doesn't raise an error:

```
ast_obj.fit_gaussian_process(fix_scale=True)
```

**Comment by kboone** [comment]
Just want to comment that I haven't forgotten about this, but I have been very busy with trying to get my dissertation submitted and haven't had time to get to it. I'll try to look into this soon.

**Comment by kboone** [comment]
I finally had the time to get to the bottom of this. The problem was that in the LBFGS minimization procedure the scale of the GP kernel was allowed to go to extreme values, and the GP evaluation then fails for numerical reasons. To fix this, I put more realistic bounds on the scale which keeps the LBFGS fitter from straying extremely far from where it should be.

As of commit f89a77db92341f4da3da2c38f2248b3ba976ea4a this should be fixed, so I'm closing this issue.

**Comment by djperrefort** [comment]
Awesome, thanks @kboone !
