### ISSUE TITLE
sequential featurize uses all cores in the machine

### ISSUE THREAD

**Issue by emilleishida** [kboone/avocado#5]
Is there a way to set up a max number of cores to be used in the sequential featurize?

**Comment by kboone** [comment]
The sequential featurize ends up using multiple cores because it makes calls to numpy and other libraries under the hood that use multiple threads by default. You can disable that/choose the number of cores to use by setting the following environment variables before you run `avocado` (or most other python codes):

```
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export OMP_NUM_THREADS=1
```
